import type { NextPage } from 'next';
import Head from 'next/head';
import Article from '../../components/Article/Article';
import ButtonGroup from '../../components/Buttons/pillShapedButton/ButtonGroup';
import Contact from '../../components/Contact/Contact';
import Footer from '../../components/Footer/Footer';
import PublicLayout from '../../components/Layouts/PublicLayout';
import Navigation from '../../components/Navigation/Navigation';
import CTA from './../../components/Buttons/CTA';
import NavigationButton from './../../components/Buttons/NavigationButton';

const Blogs: NextPage = () => {
	return (
		<div>
			<Head>
				<title>tingeworks - Blogs</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className=' mx-auto  text-londonstreet bg-slate-100'>
				<div className='container mx-5 lg:mx-10 flex flex-col lg:flex-row items-center py-32'>
					<div className='flex-1'>
						<h1 className='text-4xl lg:text-4xl xl:text-5xl font-black'>
							All our findings and announcements
						</h1>
						<p className='pt-4 text-base lg:text-xl text-gray-400 font-light'>
							Announcements, Jobs, Stories, etc.
						</p>
					</div>
					<div className='flex-1'></div>
				</div>
			</div>

			<div className='flex gap-8 mt-10 container mx-auto px-5 lg:px-10'>
				<ButtonGroup
					text='All'
					path='/all'
					style='primary'
					type='button'
				/>
				<ButtonGroup
					text='Announcements'
					path='/all'
					style='secondary'
					type='button'
				/>
				<ButtonGroup
					text='Articles'
					path='/all'
					style='secondary'
					type='button'
				/>
				<ButtonGroup
					text='Jobs'
					path='/all'
					style='secondary'
					type='button'
				/>
			</div>

			<div className='container mx-auto grid grid-cols-2'>
				<Article
					src='/public/f.png'
					title='This is tittle'
					description='a'
					alt='ks'
				/>
				<Article
					src='/public/Fruits.png'
					title='askfThis is tittle 2s'
					description='qqqqqq'
					alt='ks'
				/>
			</div>

			<Contact />

			<Footer />
		</div>
	);
};

export default Blogs;
